# Generated by Django 5.0.4 on 2024-07-05 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('gstn_no', models.CharField(max_length=15)),
                ('msme_status', models.BooleanField(default=False)),
                ('certification_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(max_length=100)),
                ('manf_plant_location', models.CharField(max_length=30)),
                ('manf_capacity', models.CharField(max_length=30)),
                ('gcv_range', models.CharField(max_length=30)),
                ('moisture', models.CharField(max_length=30)),
                ('fire', models.DecimalField(decimal_places=2, help_text='Enter a percentage, till 2 decimal places', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_material_used', models.CharField(max_length=30)),
                ('material_source', models.CharField(max_length=30)),
                ('material_price', models.DecimalField(decimal_places=2, help_text='Enter the material price, till 2 decimal places', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('binding_material', models.TextField()),
                ('untied_capacity', models.CharField(max_length=30)),
                ('No_of_loi', models.CharField(max_length=30)),
                ('pref_plant_of_unl', models.CharField(max_length=30)),
                ('dist_from_plant', models.DecimalField(decimal_places=2, help_text='Enter Distance From Plant, till 2 decimal places', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Trans_Charge', models.DecimalField(decimal_places=2, help_text='Transportation charger in Rs/Trans, till 2 decimal places.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Future_cap_add', models.BooleanField(default=False)),
                ('plant_location', models.TextField()),
                ('capacity', models.CharField(max_length=30)),
                ('GCV', models.CharField(max_length=30)),
                ('raw_material', models.CharField(max_length=30)),
                ('firm_pdf', models.FileField(upload_to='pdf/')),
            ],
        ),
    ]
